#!/bin/csh

set usr	=	mollykerwick
set sdfile = 	MOOS_test2.850171.seed
set procnum =	25
# procnum = number stations/number of processes i can do
set zcomp =	BHZ
set yr1 =	2006
set yr2 =	2006
set dy1 = 	170
set dy2 = 	190


sudo chown -R $usr .


################ make all.stns ################
cd SEED
rdseed -S -f $sdfile
awk '{print "0.0\t0.0",$5,$1,$3,$4, "\t0.0\t0.0\tBHZ"}' rdseed.stations > all.stns
mv all.stns ../.
cd ..


################ make parfiles ################
if (-d parfiles) rm -r parfiles
mkdir parfiles
makeparmfiles illap0.spec
mv *.par *.spar parfiles


################ make ttimes0 ################
if (-d ttimes0) rm -r ttimes0
mkdir ttimes0
cd ttimes0
ls ../parfiles/* > runsphfd
ex runsphfd << !
g/./s/^/sphfd par=\"/
g/./s/\$/"/
w
q
!
split -l $procnum runsphfd
ls x* > runall
ex runall << !
g/./s/^/csh /
g/./s/\$/ \&/
g/./s/\*//
w
q
!
echo "wait" >> runall
cd ..


################ make filelist.SAC ################
find SAC | grep "\.SAC" > filelist.SAC


################ make datalist.stns ##################
cd SEED
awk '{print $2, $1, var1, var2, 0, 0, var3, var4, 0, 0, 1, var5}' var1="$yr1" var2="$dy1" var3="$yr2" var4="$dy2" var5="$zcomp" rdseed.stations > datalist.stns
mv datalist.stns ../.
cd ..


################ make station.codes #################
awk '{print $2}' datalist.stns > station.codes


################ make channel.codes #################
cd SEED
sed 's/"/ /g' rdseed.stations > noquotes
awk 'FNR == 1 {print $6 "\n" $7 "\n" $8}' noquotes > channel.codes
mv channel.codes ../.
cd ..


################ run autopicker ################
# Detect
gest_beta gest_beta.spec

# Sort
sort -n detect.list > detect.list.sort

# Collect detections into events
collect_events collect_events.spec

# Window events
window_sac_beta window_sac.spec

# Onset time and location estimation
# runall_rest_beta
